### ISSUE TITLE
Precision higher than 7 not working

### ISSUE THREAD

**Issue by blackflash** [kevinongko/vue-numeric#123] opened 2022-03-07 14:41 UTC
> If you are reporting bugs please fill the form below otherwise feel free to delete the form.

## Expected Behavior
Precision higher than 7 will show proper value

## Actual Behavior
if precision 7 or higher is applied it stop working properly and its adding weird numbers. 

## Steps to Reproduce the Problem

  1. change precision in attributes of vue-numeric component ( for example in input original value is 0 with 10 decimals precision, but it renders as 0,0000000200)

## Specifications

  - Plugin Version: "vue-numeric": "^2.4.3",
  - Vue.js Version: "vue": "^2.5.0",
  - Browser: chrome
  - OS: macOs

**Comment by kevinongko** [comment] 2022-05-24 03:28
CMIIW, I think this is problem with account-js library https://github.com/openexchangerates/accounting.js

**Comment by kevinongko** [comment] 2022-05-24 03:29
duplicate of #112

**Closed by kevinongko** 2022-05-24 03:29 UTC
